language: ruby
rvm:
  - 2.2.2
sudo: false
script:
  - bundle exec rspec spec/
notifications:
  email: false
  slack:
    secure: Osa4pmUFKAY5/CFsTue1J8RLj6TIFnhz/yzUq/i5v7w1WTnjzJokHZ2erY1OcsVv/SrQBAggUfOWUVrHSYp66SaG5pYmKVIRdQBJsJ9XcfZ48dIJAn5Ylm8uoLNlUJ8Axb3pZsoc5AicwiiNVUengLkQrLaOLXeuxctr8xdP87qqNtRbQN6nJ/kHBdiYt7nHCgo/EUFCM2Eszn16bFKMBVl/2el0Zcj7GiyLCnC78Rt/HsrtsHOr6A/RCxfpM33nG+kxQkheWu/RDHTB/nmPsu/W2qLjoq3CyHjtW8l3P2zbbOQUv0xMSm9U2kQ/SOLdisllU3t3SMDwmGTdUpJlccyao2Gg4KHdSN+9SfYbtwrF0oZBPOhX4EylBRsWlYraQbngPPx6I8n5MD8IF96nLxHklM7cGejk6CX0XAdyTeDJwSmOsawgoQNh0mAEWGYolftbMII+MueUFfcLnjwRTsWtOrKTdoKPlxik3ZT1KO6uIEdYuRe6Yfn8EaqCAAk0wEI1Vl0X/oZq8UKrGkp7+97Eqn+NWHQxWxUpljq9HXS9FPi7+Z8G6t1MCrIe3gKqvK3+VFmLWUSvHBIhXjq4QBu4Zox6+lQz6nG0VX3XxprnGRxk+lH7TTuBcle2Xvrq1cV7BK+e0SpUIKsldbizfI2HQokD0FpJEPAsqe3NkGA=
addons:
  code_climate:
    repo_token:
      secure: SlBG495OVoLL1+yGDpJx8GnLaOXsu8C/gxHirvpmhrqe5yZoaIaDACsNWZMqBjKa+TqC/61qlldXA6bXXfIzV6lCCQBj1EkjgETxh0X06uOwFAj6pSUOklCz+ROoEZ7wocIVxTNUWac6MD31KXLOs6tIMmvrHg0qhp2FfVO2A2ZeMCVsLY0GqOI05hbLrX59I/sNfqdELTh/jCk3JueNO1xbTfKfNj9VzkuOtKssn57mIzPjELp/nvJXPcSDDoY8pkptRRYyG/UWdb4YLlyyT5kYc6hqhR/E60csNrEW6EkJWmd49+nFND//nxryH+Aj84o9QbgzR/9Oc34aaQrXAyWXZPWmR3phPKMusaOIOkLsY9wZqjjBUvZvaVEkZrlP/qoqeuON7cYi8zKyFc774Oo8qxFFhQ1WPGbIJfFu6mHO8rAdUiSuUj/nywjZUBo/4K1Pw5wVw7ffDnqJ9SZ0/ncnZGU8wnL3yZjbOvCZVL/N7CweL1RMqYS62cuHzBZeP6qQgtwZ/8oSMjzw7wuyMeAirspWhNoVOy9N2iRD97mKlu3+2L/6upe5OwenxOfWAL9iACA9dgG/TSMq0JbtjRAbf+nNjAoHFnBSwQ/sNOEYATjLMXcr7hO3vP7a6Izgru5sYMJb7V3e8yAXRNJjBwhkUJQb1LEtdKtIUBKkHaA=
